### PR TITLE
More test parametrization

### PR DESCRIPTION
**Pull request by Yay295**

### CODE REVIEW

**Comment by radarhere** [comment]
With these changes, you're not just extracting parameters from tests that start with loops - you're also splitting the parts that aren't in a loop into new tests, and moving outer code into loops. You're also parametrizing not just the inputs, but the expected results as well.

I don't think that every loop in a test needs to be converted to parameters. Would you mind creating this as a separate PR at https://github.com/python-pillow/Pillow instead?

**Review by hugovk — APPROVED** [review]
Looks good, thanks!

Please can you merge/rebase to include https://github.com/python-pillow/Pillow/pull/6529 and make sure the Windows tests pass?

**Review by hugovk — COMMENTED** [review]
Sorry, I reviewed the wrong PR, will check this again later.

**Comment by radarhere** [comment]
This became https://github.com/python-pillow/Pillow/pull/6531

**Pull request closed without merging**
